# .gitlab-ci.yml 文件应放在你仓库的根目录下

pages: # 必须定义一个名为 pages 的 job
  image: node:latest
  stage: build
  script:
    - npm set registry https://registry.npm.taobao.org
    - npm install
    - npm run build
    - mv dist public # 重命名 dist 文件夹 (npm run build 之后的输出位置)
    - cp public/index.html public/404.html
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  only:
    - master
